apiVersion: v1
kind: Secret
metadata:
  name: auth-api-secret
  labels:
    app: auth-api
type: Opaque
stringData:
  ConnectionStrings__FIAPGamesConnection: Server=sqlserver-auth,1433;Database=fiapgames_auth;User Id=sa;Password=CHANGE_ME;TrustServerCertificate=True
  Jwt__Key: CHANGE_ME_WITH_LONG_SECURE_JWT_KEY
  RabbitMq__UserName: CHANGE_ME
  RabbitMq__Password: CHANGE_ME
