apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-api-config
  labels:
    app: auth-api
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://+:8081
  Jwt__Issuer: FiapGamesApi
  Jwt__Audience: FiapGamesClients
  RabbitMq__HostName: rabbitmq
  RabbitMq__Port: "5672"
