apiVersion: v1
kind: Secret
metadata:
  name: auth-api-secret
  labels:
    app: auth-api
type: Opaque
stringData:
  ConnectionStrings__FIAPGamesConnection: Server=sqlserver-auth,1433;Database=fiapgames_auth;User Id=sa;Password=ChangeMe123!;TrustServerCertificate=True
  Jwt__Key: ChaveSuperSecretaFiapGamesEAD12MuitoLongaParaGarantirSeguranca123!
  RabbitMq__UserName: fiapgames
  RabbitMq__Password: FiapGames@123!
