apiVersion: v1
kind: Secret
metadata:
  name: catalog-api-secret
  labels:
    app: catalog-api
type: Opaque
stringData:
  ConnectionStrings__FIAPGamesConnection: Server=sqlserver-catalog,1433;Database=fiapgames_catalog;User Id=sa;Password=ChangeMe123!;TrustServerCertificate=True;Encrypt=False;Connect Timeout=60;ConnectRetryCount=20;ConnectRetryInterval=5
  Jwt__Key: ChaveSuperSecretaFiapGamesEAD12MuitoLongaParaGarantirSeguranca123!
  RabbitMq__UserName: fiapgames
  RabbitMq__Password: FiapGames@123!
