apiVersion: v1
kind: Service
metadata:
  name: catalog-api
spec:
  selector:
    app: catalog-api
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      nodePort: 30082
  type: NodePort
