apiVersion: v1
kind: Secret
metadata:
  name: catalog-api-secret
  labels:
    app: catalog-api
type: Opaque
stringData:
  ConnectionStrings__FIAPGamesConnection: Server=sqlserver-catalog,1433;Database=fiapgames_catalog;User Id=sa;Password=CHANGE_ME;TrustServerCertificate=True;Encrypt=False;Connect Timeout=60;ConnectRetryCount=20;ConnectRetryInterval=5
  Jwt__Key: CHANGE_ME_WITH_LONG_SECURE_JWT_KEY
  RabbitMq__UserName: CHANGE_ME
  RabbitMq__Password: CHANGE_ME
