apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-worker-config
  labels:
    app: notification-worker
data:
  ASPNETCORE_ENVIRONMENT: Development
  RabbitMq__HostName: rabbitmq
  RabbitMq__Port: "5672"
