apiVersion: v1
kind: Secret
metadata:
  name: notification-worker-secret
  labels:
    app: notification-worker
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: Server=sqlserver-notification,1433;Database=fiapgames_notifications;User Id=sa;Password=CHANGE_ME;TrustServerCertificate=True;Encrypt=False;Connect Timeout=60;ConnectRetryCount=20;ConnectRetryInterval=5
  RabbitMq__UserName: CHANGE_ME
  RabbitMq__Password: CHANGE_ME
