apiVersion: v1
kind: Secret
metadata:
  name: payment-api-secret
  labels:
    app: payment-api
type: Opaque
stringData:
  ConnectionStrings__FIAPGamesConnection: Server=sqlserver-payment,1433;Database=fiapgames_payment;User Id=sa;Password=CHANGE_ME_SQLSERVER_SA_PASSWORD;TrustServerCertificate=True;Encrypt=False;Connect Timeout=60;ConnectRetryCount=20;ConnectRetryInterval=5
  Jwt__Key: CHANGE_ME_WITH_LONG_SECURE_JWT_KEY
  RabbitMq__UserName: CHANGE_ME_RABBITMQ_USERNAME
  RabbitMq__Password: CHANGE_ME_RABBITMQ_PASSWORD
