apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver-payment
  template:
    metadata:
      labels:
        app: sqlserver-payment
    spec:
      containers:
        - name: sqlserver-payment
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              valueFrom:
                configMapKeyRef:
                  name: sqlserver-config
                  key: ACCEPT_EULA
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqlserver-secret
                  key: MSSQL_SA_PASSWORD
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$MSSQL_SA_PASSWORD\" -C -Q 'SELECT 1'"
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - mountPath: /var/opt/mssql
              name: mssql-payment-data
      volumes:
        - name: mssql-payment-data
          emptyDir: {}
